
services:
  db:
    image: postgres:latest
    container_name: test-postgres
    restart: always
    shm_size: 128mb
    network_mode: host
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: user
      POSTGRES_DB: test_db


  redis:
    image: redis:latest  # Используем легкую версию на базе Alpine
    container_name: redis_app
    restart: always
    network_mode: host
    volumes:
      - redis_data:/data     # Сохраняем данные, чтобы они не удалились с контейнером
    command: redis-server --save 60 1 --loglevel warning # Настройка автосохранения

volumes:
  redis_data:                # Создаем именованный том для данных
